spring:
  application:
    name: spring-book-react-aws
  profiles:
    active: dev

server:
  port: 8080
#  error:
#    include-message: always
#    include-binding-errors: always
#  servlet:
#    context-path: /api
